### ISSUE TITLE
Fail to update binaries on Ubuntu 18.04 

### ISSUE THREAD

**Issue by aelkhour** [Gepetto/gepetto-viewer-corba#105]
Not sure if this is the right place, but we ran into this error message while updating gepetto-viewer binaries, there seems to be a mismatch of dependency versions:

```
sudo apt-get install robotpkg-gepetto-viewer-corba
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 robotpkg-gepetto-viewer-corba : Dépend: robotpkg-gepetto-viewer (= 4.2.0) mais 4.3.0 devra être installé
```
ping @nim65s 

Btw, is there a place where we can check the versions of packages provided with the openrobots PPA for different platforms?

**Comment by nim65s** [comment]
Hi @aelkhour 
We are in the process of providing alternatives packages for both Python 2 / 3 and Qt 4 / 5.
Therefore, the name of the packages has been changed. Now, you have to install robotpkg-qt4-gepetto-viewer-corba.
Sorry I failed at announcing that.

**Comment by nim65s** [comment]
And for your second question, you might want to look at http://robotpkg.openrobots.org/rbulk/robotpkg/all.html

**Comment by nim65s** [comment]
But the binary packages are only created for ubuntu: http://robotpkg.openrobots.org/debian.html

**Comment by aelkhour** [comment]
Noted, thanks!
