### ISSUE TITLE
Unable to create a window with a given name

### ISSUE THREAD

**Issue by nmansard** [Gepetto/gepetto-viewer-corba#107]
Hi,
I am using Gepetto-gui with the helper functions implemented in the Pinocchio::RobotWrapper python class. They are using pretty classical methods of the IDL API, so I directly put the Pinocchio code here. Tell me if you want be to be more agnostic.

I typically create the window in gepetto-gui using the "pinocchio" name. 
robot.initDisplay(loadModel=True,windowName='pinocchio') # windowName uses here the default argument
However, since some time, gepetto-gui silently reject this request, or more specifically, creates the windows internally but does not display it. The windows is then in the node list, but nothing is displayed. 

Yet it is working if I name the window differently.
robot.initDisplay(loadModel=True,windowName='crocoddyl')
In that case, the window is properly displayed. 

It seems that there are some kind of default configuration file for gepetto-gui, that I involuntarily change. I tried to re-install gepetto corba, but this does not change anythink.

 I am with the APT binary packages on qt4.

Any idea?

**Comment by jmirabel** [comment]
When quitting, the GUI saves the some information about the size and visibility of some widgets so that, when you reopen it, you have the same layout as when you last closed it. It is generally very convenient but I agree that in your case, it is rather annoying. It's not hard to bypass it though.

The following steps should solve your issue:
- open the GUI
- create the window
- make it visible
- close the GUI

**Comment by jmirabel** [comment]
To reset the behavior, you can also remove the file prefix/etc/gepetto-gui/.state.conf

**Comment by nmansard** [comment]
I did not understand how to "make it visible". But I understood very well how to remove the conf file :)

Thanks!

**Comment by jmirabel** [comment]
> I did not understand how to "make it visible".

I realize it's not trivial. As the question was just asked to me again, I post the solution here:
- open any window of the Window menu (for instance, Body tree),
- right click on the top horizontal bar of the widget (the bar containing the title and the button to close it).
