### ISSUE TITLE
gepetto-gui

### ISSUE THREAD

**Issue by jcarpent** [Gepetto/gepetto-viewer-corba#111]
@jmirabel Why gepetto-gui is compiled with C++11 standard?

**Comment by jmirabel** [comment]
I don't know. I don't remember having done changes in that direction (although I have nothing against).

**Comment by jcarpent** [comment]
The issue is that gepetto-viewer is not compiler with this option, making gepetto-gui not able to find some symbols, related to std:: or boost:: shared_ptr

**Comment by jmirabel** [comment]
I do not understand what you said. There are no mention of C++ 11 in the CMakeLists... I don't know how it can have chosen to use C++ 11.

**Comment by jcarpent** [comment]
Me neither. But, a `std=gnu++11` appears when building only the target `gepetto-gui` and I was not able to find where does it come from. Maybe a dependency? But, again, I was not identify it.

**Comment by jmirabel** [comment]
> Maybe a dependency?

that's possible if you updated something, like OSG.

You can force compilation with C++ 11. It should work fine.

**Comment by jcarpent** [comment]
But what is weird is that it is only appearing for a specific target, while the others have the same dependencies.

**Comment by jmirabel** [comment]
Did you try to recompile in a clean build directory ?

**Comment by jcarpent** [comment]
Yes. Several times.

**Comment by jmirabel** [comment]
You can check the pc file of openscenegraph openthreads openscenegraph-osgqt and omniORB4.

**Comment by jcarpent** [comment]
I've done it. No gnu++11 forcing.

**Comment by jmirabel** [comment]
Very mysterious.
Are the flags taken recursively ? If so, did you check the dependencies written in those pc files ?

**Comment by jmirabel** [comment]
I just discovered this commit f53e082da1cd9a8a0a94dd920e318c98e73f8c57 from @nim65s .
I guess it is related to your issue...

**Comment by nim65s** [comment]
This commit was pushed since https://github.com/Gepetto/gepetto-viewer-corba/issues/113#issuecomment-469854530.
I wanted to revert it, but did not had time.

**Comment by nim65s** [comment]
So no, this commit is not related to the issue, as it was not here when this issue appeared.

**Comment by jmirabel** [comment]
Sorry about that.
