### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by jcarpent** [Gepetto/gepetto-viewer-corba#113]
After merging #112, it would be nice to make a new release.
@nim65s @jmirabel Is it fine for you?

**Comment by nim65s** [comment]
I will finish the 5.1.2 first, and if you need it for OSX, we will be able to make one just after.

**Comment by jcarpent** [comment]
Ok. Can push the tags too. I will make the rest.

**Comment by nim65s** [comment]
done

**Comment by jcarpent** [comment]
Thanks a lot!
