### ISSUE TITLE
Compatibility with Qt4 broken

### ISSUE THREAD

**Issue by ksyy** [Gepetto/gepetto-viewer-corba#115]
It appears that the inclusion of `<QtGui/qopengl.h>` in [3dc7f16](https://github.com/Gepetto/gepetto-viewer-corba/commit/3dc7f167ec9c7e3bca6c54180bf153dbdeb5b613) breaks the compatibility with Qt4, because it only exists in Qt5 and therefore, the project cannot compile.

I suppose this is not wanted…

**Comment by jcarpent** [comment]
Sorry, I have introduced this bug. It should not be so hard to recover from it. @ksyy Can you take it in charge?

**Comment by jmirabel** [comment]
from https://stackoverflow.com/questions/24899558/how-to-check-qt-version-to-include-different-header
```c++
#include <QtGlobal>
#if QT_VERSION >= 0x050000
    #include <QApplication>
#else
    #include <QtGui/QApplication>
#endif
```

**Comment by ksyy** [comment]
Thanks @jmirabel
