### ISSUE TITLE
Gepetto-viewer-corba not compiling anymore

### ISSUE THREAD

**Issue by proyan** [Gepetto/gepetto-viewer-corba#117]
I'm not sure if this is related to #115 or not, but here it is:
I'm on the current devel (65b8fb828d5a9e2bafd100bc78e14d4ccc63d3a9). It is not compiling anymore.
I get the following error:

`CMakeFiles/gepetto-gui.dir/gui/node-action.cc.o: In function `gepetto::gui::NodeAction::act(bool)':
node-action.cc:(.text+0x9bb): undefined reference to `graphics::WindowManager::attachCameraToNode(std::shared_ptr<graphics::Node>)'
`
windows-manager.cc:(.text+0x2094): undefined reference to `graphics::WindowsManager::addNode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<graphics::Node>, std::shared_ptr<graphics::GroupNode>)'

Please let me know what info you need about versions etc in order to debug/help me solve it.

**Comment by proyan** [comment]
my cmake gives the following output:

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- omniORB4 >= 4.1.4 is required.
-- Checking for module 'omniORB4 >= 4.1.4'
--   Found omniORB4 , version 4.1.6
-- Pkg-config module omniORB4 v4.1.6 has been detected with success.
-- openscenegraph >= 3.2 is required.
-- Checking for module 'openscenegraph >= 3.2'
--   Found openscenegraph , version 3.2.1
-- Pkg-config module openscenegraph v3.2.1 has been detected with success.
-- openscenegraph-osgQt is required.
-- Checking for module 'openscenegraph-osgQt'
--   Found openscenegraph-osgQt, version 3.2.1
-- Pkg-config module openscenegraph-osgQt v3.2.1 has been detected with success.
-- openthreads >= 2.6 is required.
-- Checking for module 'openthreads >= 2.6'
--   Found openthreads , version 3.2.1
-- Pkg-config module openthreads v3.2.1 has been detected with success.
-- gepetto-viewer >= 4.3.0 is required.
-- Checking for module 'gepetto-viewer >= 4.3.0'
--   Found gepetto-viewer , version 4.4.1
-- Pkg-config module gepetto-viewer v4.4.1 has been detected with success.
-- urdfdom is required.
-- Checking for module 'urdfdom'
--   Found urdfdom, version 0.4.0
-- Pkg-config module urdfdom v0.4.0 has been detected with success.
-- Boost version: 1.58.0
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   regex
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- PythonInterp: /usr/bin/python
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- PythonLibraries: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PythonLibraryDirs: /usr/lib/x86_64-linux-gnu
-- PythonLibVersionString: 2.7.12
-- Could NOT find PythonQt (missing:  QtAll) 
-- qgv is optional.
-- Checking for module 'qgv'
--   No package 'qgv' found
-- Skipping PythonQt settings
-- Doxygen rendering: using LaTeX backend
-- Configuring done
-- Generating done

**Comment by nim65s** [comment]
Do you really need to build it ? Can't you just use the binary version ?
It is just a `sudo apt install robotpkg-py27-qt4-gepetto-viewer-corba` away from working :)

Otherwise, your issue might be related to the push I made too fast. You can try to remove this line: 
https://github.com/Gepetto/gepetto-viewer-corba/blob/65b8fb828d5a9e2bafd100bc78e14d4ccc63d3a9/CMakeLists.txt#L22

**Comment by jcarpent** [comment]
Yes, this is related to #111 in fact.

**Comment by jmirabel** [comment]
Does #118 fix your problem ?

**Comment by jmirabel** [comment]
@nim65s It's actually a good thing that some people uses the source version. This allows to detect some bugs earlier.

**Comment by nim65s** [comment]
IMO the CI should detect those bugs, before they affect other users.

If we wanted to have a good quality software, I agree with you, it would be better to have a lot of people use it in a wide variety of situations, and ensure that it works for everybody everywhere.
If we wanted to let our users have something that just works and don't slow them with our issues, it would be better to have one and only one official way to deal with everything.

If we wanted both… We would need more engineers :)

**Comment by jmirabel** [comment]
This one, yes, CI would have done the job. But for a GUI, there are many things it can't check.

The question is simpler than this. People have the choice of using sources or binaries. They know the pros and cons of each. We let them choose the method they want and I am happy that some uses the sources as it gives us some feedback. That's it.

**Comment by proyan** [comment]
@jmirabel @nim65s It works now. Thanks.
I'll close this issue.
