### ISSUE TITLE
[Ubuntu 18.04] Cannot import gepetto

### ISSUE THREAD

**Issue by aelkhour** [Gepetto/gepetto-viewer-corba#122]
## Versions

```
robotpkg-py27-qt4-gepetto-viewer is already the newest version (4.5.0).
robotpkg-py27-qt4-gepetto-viewer-corba is already the newest version (5.2.1).
```

## Behavior

```
In [1]: import gepetto
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b6e9c433b0e8> in <module>()
----> 1 import gepetto

/opt/openrobots/lib/python2.7/site-packages/gepetto/__init__.py in <module>()
     16 # <http://www.gnu.org/licenses/>.
     17 
---> 18 from .color import Color
     19 from .quaternion import Quaternion
     20 from .corbaserver import Error

/opt/openrobots/lib/python2.7/site-packages/gepetto/color.py in <module>()
     18 # <http://www.gnu.org/licenses/>.
     19 
---> 20 from .corbaserver import Color

/opt/openrobots/lib/python2.7/site-packages/gepetto/corbaserver/__init__.py in <module>()
----> 1 from .gepetto.corbaserver import GraphicalInterface
      2 from .gepetto__POA.corbaserver import NodeCallback as POA_NodeCallback
      3 from .gepetto import Error
      4 
      5 from .client import Client

/opt/openrobots/lib/python2.7/site-packages/gepetto/corbaserver/gepetto/__init__.py in <module>()
      7 
      8 # ** 1. Stub files contributing to this module
----> 9 import gepetto.corbaserver.graphical_interface_idl
     10 
     11 # ** 2. Sub-modules

/opt/openrobots/lib/python2.7/site-packages/gepetto/corbaserver/graphical_interface_idl.py in <module>()
    770 _0_gepetto.corbaserver._objref_GraphicalInterface.registerNodeCallback.im_func.__doc__ = _0_gepetto.corbaserver.GraphicalInterface.registerNodeCallback__doc__
    771 _0_gepetto.corbaserver.GraphicalInterface.__doc__ = _0_gepetto.corbaserver.GraphicalInterface__doc__
--> 772 _0_gepetto.corbaserver._objref_GraphicalInterface.__doc__ = _0_gepetto.corbaserver.GraphicalInterface__doc__
    773 _0_gepetto.__doc__ = _0__GlobalIDL.gepetto__doc__
    774 

AttributeError: attribute '__doc__' of 'type' objects is not writable
```

**Comment by nim65s** [comment]
Thanks for the report. 

I am able to reproduce this issue, and removing all lines with `.__doc__ =` workaround it, if you need a quick and dirty fix.

@jmirabel : do you want to work on that, or should I implement one of the solutions given here: https://stackoverflow.com/a/13937525 ?

**Comment by nim65s** [comment]
Also, this bug comes from the fact that the `_objref_GraphicalInterface` class inherits from the `omniORB.CORBA.Object`, which in turn inherits from `object` in the omniORB version from 18.04 and not 16.04

**Comment by jmirabel** [comment]
> @jmirabel : do you want to work on that, or should I implement one of the solutions given here: https://stackoverflow.com/a/13937525 ?

@nim65s  When the support for Python 3 will be fully functional, could you check whether this happens for Python 3 as well ?

If it happens only with Python 2, then, I suggest to skip the generation of the docstring for Python 2. It only a bit of CMake I think.
Otherwise, we will discuss another solution.

**Comment by nim65s** [comment]
@jmirabel : it doesn't happen only with Python 3, it happens with omniORB 4.2

**Comment by jmirabel** [comment]
I think it isn't too bad not to generate docstrings for Python 2 then.

**Comment by jmirabel** [comment]
The following CMake macro call must be changed accordingly. Options `-p...` and `-b...` must be removed. @nim65s can you address this ?
```cmake
  GENERATE_IDL_PYTHON (gepetto/viewer/corba/${IDL}
    ${CMAKE_SOURCE_DIR}/idl/gepetto/viewer
    ARGUMENTS
    -p${CMAKE_SOURCE_DIR}/cmake/hpp/idl
    -bomniidl_be_python_with_docstring
    -C${CMAKE_CURRENT_BINARY_DIR}
    -K
    -Wbpackage=gepetto.corbaserver
    )
```

**Comment by nim65s** [comment]
yes

**Comment by ylabbe** [comment]
I had the same issue with python 3 and had to remove the lines in the generated files. 
Same issue in the hpp repositories like https://github.com/humanoid-path-planner/hpp-manipulation-corba

**Comment by wxmerkt** [comment]
We are having the same problem with py27 all installed from robotpkg on Ubuntu 18.04 (also, all robotpkg Python packages are installed into `site-packages` and not as usual on debian into `dist-packages`?). 

Is there a timeline for an update to the binaries to fix this issue?

**Comment by nim65s** [comment]
I finished all tests about this and sent a PR this morning, so about the timeline we are only waiting for the maintainer of robotpkg to review it.

About the path, [Python documentation](https://docs.python.org/fr/3/library/site.html) says to put modules in `lib/pythonX.Y/site-packages`, but Debian chose `lib/pythonX/dist-packages` instead. I don't understand why, and I don't know if this would be useful for robotpkg to adapt its `PYTHON_SITELIB` to the current distribution.
