### ISSUE TITLE
Making videos with a script

### ISSUE THREAD

**Issue by andreadelprete** [Gepetto/gepetto-viewer-corba#125]
In the good old days there was only one way to make a video with gepetto-viewer, which was to use to method `startCapture`, which would start saving screenshots on your disk, and then you could use ffmpg to generate a video from those images.

Now I see several new methods:
* captureFrame
* captureTransform
* captureTransformOnRefresh

Can anybody help me figure out the best way to make videos?
Beware I need to do it by scripting, I cannot use the handy new button on the GUI.

**Comment by jmirabel** [comment]
The GUI using startCapture and stopCapture. It has never been removed so it should be available.

**Comment by jmirabel** [comment]
Note that you can also do it with `captureFrame`, which saves an image at each call, with the following pros and cons compared to `startCapture`, `stopCapture`:

- pros: you have a thin control of when the frame are taken. With start/stop capture, you do not control when the frames are taken. You cannot be sure that you will have one frame per call to refresh.
- cons: it is more intrusive. If needed, we could easily add a captureFrameOnRefresh, which makes it non-intrusive.

**Comment by andreadelprete** [comment]
Ok, clear! I think for my application I'll use `captureFrame`. Thanks @jmirabel !
