### ISSUE TITLE
Simple server set up

### ISSUE THREAD

**Issue by nmansard** [Gepetto/gepetto-viewer-corba#135]
This is what it takes to create a new Gepetto-Viewer window from python
```
def GepettoViewerServer(windowName="python-pinocchio", sceneName="world", loadModel=False):
    """
    Init gepetto-viewer by loading the gui and creating a window.
    """
    import gepetto.corbaserver
    try:
        viewer = gepetto.corbaserver.Client()
        gui = viewer.gui

        # Create window
        window_l = gui.getWindowList()
        if windowName not in window_l:
            gui.windowID = gui.createWindow(windowName)
        else:
            gui.windowID = gui.getWindowID(windowName)

        # Create scene if needed
        scene_l = gui.getSceneList()
        if sceneName not in scene_l:
            gui.createScene(sceneName)
            gui.addSceneToWindow(sceneName, gui.windowID)

        gui.sceneName = sceneName

        return gui

    except Exception:
        print("Error while starting the viewer client. ")
        print("Check whether gepetto-gui is properly started")
```

I have to copy this function quite often in my codes. 

Questions:
- would you agree that this is the "minimal" way of creating a new viewer (or connecting again to it if it already exists)?
- if so, could we put this method somewhere in the Python API of Gepetto-Viewer corba, to simplify the use of the software?

**Comment by jmirabel** [comment]
When a window is create, a group with the same name is also added so a shorter version is
```python
def GepettoViewerServer(windowName="python-pinocchio", sceneName="world", loadModel=False):
    """
    Init gepetto-viewer by loading the gui and creating a window.
    """
    import gepetto.corbaserver
    try:
        viewer = gepetto.corbaserver.Client()
        gui = viewer.gui

        # Create window
        if windowName not in  gui.getWindowList():
            gui.windowID = gui.createWindow(windowName)
        gui.windowID = gui.getWindowID(windowName)
        # A group node called windowName has been created.
        return gui

    except Exception:
        print("Error while starting the viewer client. ")
        print("Check whether gepetto-gui is properly started")
```

Now there are several ways of simplifying this. The things I had in mind are:
- Use *windowName* as an integer (I was the one that changed the string to integer but it was a mistake). Then, `createWindow` should just create a window if windowName does not exist.
- The class Client should be removed. The only thing which is accessed is its member gui... This was copy-pasted from hpp-corbaserver.

This would make your code look like:
```python
def GepettoViewerServer(windowName="python-pinocchio", sceneName="world", loadModel=False):
    """
    Init gepetto-viewer by loading the gui and creating a window.
    """
    import gepetto.corbaserver
    try:
        gui = gepetto.corbaserver.Client()
        gui.createWindow(windowName)
        return gui

    except Exception:
        print("Error while starting the viewer client. ")
        print("Check whether gepetto-gui is properly started")
```
We cannot do better.

**Comment by jmirabel** [comment]
Note that the argument *sceneName* has been removed.

**Comment by nmansard** [comment]
Currently, Pinocchio (robot-wrapper) is creating a window name "python-pinocchio" and a scene named "world". I have to keep the same namings, or change Pinocchio code. 

The last version that you show is clearly much better. In particular, directly accessing to viewer.gui is more intuitive. Would it be costly?

Yet, we can do better by putting the wrapper function inside gepetto-viewer-corba. This is also much less work.

**Comment by jmirabel** [comment]
> Currently, Pinocchio (robot-wrapper) is creating a window name "python-pinocchio" and a scene named "world". I have to keep the same namings, or change Pinocchio code.

I don't think the window name matters much in pinocchio. Changing the scene name however would have more impact on users.

> The last version that you show is clearly much better. In particular, directly accessing to viewer.gui is more intuitive. Would it be costly?

From the developers point of view, no. From the user perspective, neither if we still provide the Client class for backward compatibility.

**Comment by jmirabel** [comment]
With #136 
```
def GepettoViewerServer(windowName="python-pinocchio", loadModel=False):
    """
    Init gepetto-viewer by loading the gui and creating a window.
    """
    import gepetto.corbaserver
    gui = gepetto.corbaserver.gui_client(True)
    if gui is not None:
      gui.createWindow(windowName)
    return gui
```

**Comment by jmirabel** [comment]
The second point will wait a bit.

**Comment by nmansard** [comment]
Don't you think we could put this function (or possibly the extended version which creates a basic scene with an arbitrary name) in gepetto-viewer-corba package?

**Comment by jmirabel** [comment]
With the proposed changes, the code that called
```python
gui = GepettoViewerServer('window','scene')
```
can be replaced by
```python
import gepetto.corbaserver
gui = gepetto.corbaserver.gui_client(window_name='window', dont_raise=True)
gui.createGroup('scene')
gui.addToGroup("scene", "window")
```

The extra scene is a misuse of the API. I don't think it should go into this package.

**Comment by jmirabel** [comment]
I believe this is now solved. I added the code snippet to the main page documentation.
