### ISSUE TITLE
Packages for Ubuntu 20.04

### ISSUE THREAD

**Issue by aelkhour** [Gepetto/gepetto-viewer-corba#143]
We are looking to migrate our codebase on Ubuntu 20.04 LTS, and it seems there are no compatible binary packages for gepetto-gui.

Are there any plans to provide packages for Ubuntu 20.04 and python 3.8?

**Comment by jmirabel** [comment]
Already ! Congrats.

This discussion should be moved to some robotpkg channel. 20.04 is not yet supported by robotpkg build farm (see http://robotpkg.openrobots.org/debian.html). @nim65s may know what channel should be followed to be notified when it is ready.

**Comment by nim65s** [comment]
Python 3.8 is already available on robotpkg. For Ubuntu 20.04, I just created an issue to track advancement:
https://git.openrobots.org/issues/252

**Comment by aelkhour** [comment]
Thanks @jmirabel and @nim65s.

Feel free to close this issue if you prefer, I will follow the robotpkg issue directly.

**Comment by nim65s** [comment]
@aelkhour : that should be OK now: http://robotpkg.openrobots.org/rbulk/robotpkg/graphics/py-qt-gepetto-viewer-corba

**Comment by aelkhour** [comment]
Thanks @nim65s ! 

> But now this is only a matter of apt-install dependencies :)

What do you mean exactly by the above comment ? That it's a matter of build time before the packages are available?

**Comment by jmirabel** [comment]
I guess he meant that the build farm is ready (this was step 1) and currently provides packages that are compatible with the dependency provided by ubuntu 20.04. As they are different from 18.04, there may be some update to do in some places to make it compatible (this is step 2).

**Comment by aelkhour** [comment]
OK thanks @jmirabel, I'll patiently wait and monitor the build status for py38.

**Comment by aelkhour** [comment]
Sorry to bother you again with this @nim65s, but I was wondering if there were any news for the py38 packages.

Looking at the [build status](http://robotpkg.openrobots.org/rbulk/robotpkg/graphics/py-qt-gepetto-viewer-corba/) and a [build log](http://robotpkg.openrobots.org/rbulk/robotpkg/graphics/py-qt-gepetto-viewer-corba/py38-qt5-gepetto-viewer-corba-5.4.0/Ubuntu-20.04-x86_64/bulk.html), it seems as if this is an issue of missing python38 alternative in robotpkg, but I'm not sure.

PS: I tried to create an account on openrobots a couple of days ago so that I can directly open an issue there (I mentioned you as LAAS referral) and avoid additional noise here, but I've been waiting for administrator permission since.

**Comment by nim65s** [comment]
Hi @aelkhour ,

We have found a harder issue on this: since 20.04, while we were waiting to get the Qt5 bindings instead of the Qt4 ones, ubuntu's openscenegraph package doesn't any Qt bindings anymore. While the package from Debian is providing Qt5. I just don't understand that.

ref https://bugs.launchpad.net/ubuntu/+source/openscenegraph/+bug/1279268

I will workaround that by providing osgqt in robotpkg, this should fix the issue. I'm planning to do that next week.

ref https://git.openrobots.org/issues/255

I'll validate your account on openrobots.

**Comment by aelkhour** [comment]
OK thanks for the update.
