### ISSUE TITLE
Gepetto viewer often crashes after system update

### ISSUE THREAD

**Issue by cmastalli** [Gepetto/gepetto-viewer-corba#147]
Hi guys,

I have updated today both `gepetto-viewer-corba` and `gepetto-viewer`. This is the information of my system:
 - installation: robotpkg
 - OS: Ubuntu 18.04
 - Python 2
 - robotpkg-py27-qt4-gepetto-viewer-corba:amd64 5.4.0
 - robotpkg-py27-qt4-gepetto-viewer:amd64 4.9.0

And this is the message error that appears sometimes when I run my Python script:
```bash
    self.robot.viewer.gui.setVector3Property(forceName, "Scale", [1. * forceMagnitud, 1., 1.])
  File "/opt/openrobots/lib/python2.7/site-packages/gepetto/corbaserver/graphical_interface_idl.py", line 549, in setVector3Property
    return self._obj.invoke("setVector3Property", _0_gepetto.corbaserver.GraphicalInterface._d_setVector3Property, args)
omniORB.CORBA.COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)
```

**Comment by cmastalli** [comment]
A short comment - I confirm that if I downgrade both packages, as
```bash
sudo apt install robotpkg-py27-qt4-gepetto-viewer=4.8.0 robotpkg-py27-qt4-gepetto-viewer-corba=5.3.2
```
then the problem disappears.

Do you know what it is happening here @nim65s, @jmirabel?

**Comment by jmirabel** [comment]
If it doesn't crash systematically, then, I think I know what's happening (a synchronization issue in the properties). I will do a quick test later next week.

As of now, I don't have the problem on my computer. It may be because I use Qt5 and not Qt4, but I am not sure.

**Comment by cmastalli** [comment]
Thank you for taking care.
Note that this is not urgent for me since I downgrade the software.
Just keep me updated :)
