### ISSUE TITLE
gepetto-viewer none-exposed window 

### ISSUE THREAD

**Issue by hammoudbilal** [Gepetto/gepetto-viewer-corba#151]
Hi, 

I am using the usual 'pinocchio.RobotWrapper.initViewer()' to display a robot in gepetto-viewer, 
recently I get the following error 

```
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
omniORB: (3) 2020-09-14 13:13:52.994600: From endpoint: giop:tcp:[::1]:57524. Detected GIOP 1.0 protocol error in input message. giopImpl10.cc:491. Connection is closed.
omniORB: (3) 2020-09-14 13:13:52.994819: To endpoint: giop:tcp:[::1]:57524. Send GIOP 1.0 MessageError because a protocol error has been detected. Connection is closed.
omniORB: (4) 2020-09-14 13:13:52.994892: Error: received an invalid zero length string.
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```

any idea what might be going wrong ?

**Comment by jmirabel** [comment]
I suspect you have several version of omniorb installed. I guess the server uses the one from robotpkg while the Python client only finds the one from the main repos.

You can check what is installed with `apt list "*omniorb*"`.

**Comment by hammoudbilal** [comment]
thanks alot, I'll close this issue
