### ISSUE TITLE
Geppetto installation in Ubuntu 22.04

### ISSUE THREAD

**Issue by sharathmatada** [Gepetto/gepetto-viewer-corba#183]
I'm getting the following issue when I try to install gepetto
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Reading package lists... Done
W: http://robotpkg.openrobots.org/packages/debian/pub/dists/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://ppa.launchpadcontent.net/sylvain-pineau/kazam/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details

**Comment by nim65s** [comment]
lines about robotpkg are only warnings, you can ignore them.
lines with real errors are about https://ppa.launchpadcontent.net/sylvain-pineau/kazam/ubuntu/ and have nothing to do with us.
