### ISSUE TITLE
Severe performance loss when switching from gepetto-viewer to gepetto-gui

### ISSUE THREAD

**Issue by aelkhour** [Gepetto/gepetto-viewer-corba#94]
We have recently switched to installing the official gepetto-viewer binaries and using gepetto-gui along side pinocchio v2.0.0-alpha.

After switching from gepetto-viewer to gepetto-gui, we have noticed a severe performance loss when running the same script which relies on `pinocchio.RobotWrapper.display()`, by at least one order of magnitude in terms of script execution time.

The slowdown was noticed even when we are loading the robot meshes (via `pinocchio.RobotWrapper.loadDisplayModel()`), where instead of having a quasi-instantaneous display of the robot, we can see the meshes appear progressively and the whole loading time taking more than one second.

We can provide more information if you give us pointers as to what to look for.

**Comment by aelkhour** [comment]
We are running on Ubuntu 18.04. pinocchio v2.0.0-alpha is built in Release by us, while gepetto-viewer-corba and dependencies are installed via apt-get, so I would assume they are built in Release.

We installed everything using the following instructions:

```sh
sudo sh -c "echo 'deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub bionic robotpkg' >> /etc/apt/sources.list.d/robotpkg.list"
curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install robotpkg-gepetto-viewer-corba
```

**Comment by jmirabel** [comment]
I haven't tested it on 18.04. There are two OSG versions (3.2 and 3.4) on 18.04. It should work with both.
Can you check the one you used (with ldd on gepetto-gui) ? Also, can you provide the details about the version in menu Help > About

I suspect robotpkg is not up-to-date. @nim65s I checked the versions on robotpkg (using //robotpkg.openrobots.org/packages/debian/pub/dists/trusty/robotpkg/binary-amd64/Packages and //robotpkg.openrobots.org/packages/debian/pub/dists/bionic/robotpkg/binary-amd64/Packages). On trusty, it is 1.0.0 and on bionic, 2.2.0. It seems far from version 5.0.0. Is it expected ?

**Comment by nim65s** [comment]
@jmirabel : I just made a `sudo apt-get install robotpkg-gepetto-viewer-corba` and got `5.0.0`

**Comment by aelkhour** [comment]
`gepetto-viewer-corba` depends on `libopenscenegraph-dev`, which has version 3.2.3. Apparently even if  `libopenscenegraph-3.4-dev` is installed, it is automatically removed when installing `gepetto-viewer-corba`.

I confirm that we are using gepetto-gui v5.0.0 according to the help menu.

Do you have some kind of minimal python script benchmark so that we can compare performance ?

**Comment by jmirabel** [comment]
Thanks to both of you for the feedback.

> Do you have some kind of minimal python script benchmark so that we can compare performance ?

Not that I know of.

Can you provide a helpful output with https://docs.python.org/2/library/profile.html on the high level functions which takes time ?

**Comment by aelkhour** [comment]
I ran the following script through `python -m cProfile -s cumtime test.py` :

```python
import pinocchio

# Set urdf path and package dirs.
urdf_path = 'myurdf.urdf'
package_dirs = ['mydir']

# Build robot model (no viewer needed)
robot = pinocchio.RobotWrapper()
robot.initFromURDF(urdf_path, package_dirs, pinocchio.JointModelFreeFlyer())

# Load robot display model in viewer (without floor)
robot.initDisplay('python-pinocchio', 'world', loadModel=True)

# Add floor for convenience.
robot.viewer.gui.addFloor('hpp-gui/floor')

for i in range (10000):
    # Update robot configuration in viewer (neutral configuration).
    robot.display(robot.q0)
```

Result is:

```
         5493406 function calls (5492249 primitive calls) in 11.789 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.047    0.047   11.789   11.789 test.py:1(<module>)
    10000    1.766    0.000   11.583    0.001 robot_wrapper.py:328(display)
   160070    4.968    0.000    4.968    0.000 {method 'invoke' of '_omnipy.PyObjRefObject' objects}
   150000    0.172    0.000    4.730    0.000 graphical_interface_idl.py:404(applyConfiguration)
   150000    1.724    0.000    4.424    0.000 utils.py:43(se3ToXYZQUAT)
   450064    0.502    0.000    1.381    0.000 defmatrix.py:212(__new__)
  1050000    1.009    0.000    1.319    0.000 defmatrix.py:280(__getitem__)
   450065    0.322    0.000    0.694    0.000 {method 'view' of 'numpy.ndarray' objects}
  2402952    0.597    0.000    0.597    0.000 {isinstance}
    10001    0.012    0.000    0.420    0.000 graphical_interface_idl.py:410(refresh)
   450066    0.270    0.000    0.372    0.000 defmatrix.py:258(__array_finalize__)
        6    0.014    0.002    0.186    0.031 __init__.py:1(<module>)
   150060    0.158    0.000    0.158    0.000 robot_wrapper.py:245(getViewerNodeName)
        1    0.001    0.001    0.136    0.136 __init__.py:17(<module>)
        1    0.002    0.002    0.112    0.112 __init__.py:106(<module>)
        1    0.000    0.000    0.099    0.099 add_newdocs.py:10(<module>)
        1    0.001    0.001    0.079    0.079 type_check.py:3(<module>)
    10000    0.065    0.000    0.065    0.000 robot_wrapper.py:130(forwardKinematics)
        1    0.001    0.001    0.040    0.040 _internal.py:6(<module>)
        1    0.001    0.001    0.025    0.025 __init__.py:7(<module>)
        1    0.000    0.000    0.023    0.023 __init__.py:10(<module>)
        1    0.011    0.011    0.023    0.023 robot_wrapper.py:17(<module>)
        1    0.001    0.001    0.023    0.023 py3k.py:4(<module>)
        1    0.003    0.003    0.023    0.023 pathlib.py:1(<module>)
    10000    0.020    0.000    0.020    0.000 robot_wrapper.py:203(updateGeometryPlacements)
        1    0.000    0.000    0.017    0.017 decorators.py:5(<module>)
        1    0.000    0.000    0.017    0.017 decorators.py:15(<module>)
       33    0.000    0.000    0.017    0.001 re.py:230(_compile)
       29    0.000    0.000    0.017    0.001 re.py:192(compile)
        1    0.005    0.005    0.017    0.017 urllib.py:23(<module>)
        1    0.002    0.002    0.016    0.016 utils.py:4(<module>)
       25    0.000    0.000    0.016    0.001 sre_compile.py:567(compile)
```

**Comment by jmirabel** [comment]
I am surprised about this line:
```
   150000    1.724    0.000    4.424    0.000 utils.py:43(se3ToXYZQUAT)
```
It shouldn't do anything else that copy 7 floating point numbers...

**Comment by jmirabel** [comment]
Is eigenpy in release mode ?

**Comment by aelkhour** [comment]
Sorry for posting this quickly without any further comments.

I confirm that eigenpy is built in Release mode.
I am as surprised as you that this `se3ToXYZQUAT` takes so much time in total. This said it amounts to 29 microseconds per call, so I'm not sure it's abnormal. @jcarpent do you have any inputs regarding this issue ?

The same remark applies to `applyConfiguration`.

**Comment by jmirabel** [comment]
I am also surprised by `__getitem__` taking so long (about 1us per call)... Can you run the unit-tests in eigenpy and report the timings ?
On my computer:
```
$ make test
Running tests...
Test project /home/jmirabel/devel/demo/src/eigenpy/build-rel
    Start 1: matrix
1/6 Test #1: matrix ...........................   Passed    0.04 sec
    Start 2: geometry
2/6 Test #2: geometry .........................   Passed    0.04 sec
    Start 3: ref
3/6 Test #3: ref ..............................   Passed    0.04 sec
    Start 4: py-matrix
4/6 Test #4: py-matrix ........................   Passed    0.04 sec
    Start 5: py-geometry
5/6 Test #5: py-geometry ......................   Passed    0.04 sec
    Start 6: py-switch
6/6 Test #6: py-switch ........................   Passed    0.04 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) =   0.25 sec

```

**Comment by aelkhour** [comment]
Tests on `eigenpy v1.4.5`:

```
    Start 1: matrix
1/5 Test #1: matrix ...........................   Passed    0.13 sec
    Start 2: geometry
2/5 Test #2: geometry .........................   Passed    0.10 sec
    Start 3: ref
3/5 Test #3: ref ..............................   Passed    0.10 sec
    Start 4: py-matrix
4/5 Test #4: py-matrix ........................   Passed    0.11 sec
    Start 5: py-geometry
5/5 Test #5: py-geometry ......................   Passed    0.11 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =   0.55 sec
```

So there is roughly a 200% difference. This said, our scripts which do not need visualization and rely heavily on `eigenpy` are running at a satisfying speed for now, so I'm not sure that it's the main culprit.

**Comment by jmirabel** [comment]
From the viewer side, nothing seems wrong to me.
You can play with the following script to check it:
```py
from gepetto.corbaserver import Client
import time
cl = Client()
wid = cl.gui.createWindow("name")
cl.gui.createGroup ("g")
cl.gui.addSceneToWindows('g', wid)
cl.gui.addMesh("g/mesh", path)
for i in range(1000):
  time.sleep(0.01)
  cl.gui.applyConfiguration("g/mesh", [ 0.001*i, 0, 0, 0, 0, 0, 1])
  cl.gui.refresh()
```

**Comment by matthieuvigne** [comment]
Like @aelkhour, I've seen a performance drop when updating the viewer (we share the same setup). I'll try to add my own input.

Note that we are switching from ```gepetto-viewer 1.1.0``` and ```gepetto-viewer-corba 1.1.0``` to the current version - which is quite a big jump. I've compared the old version and the current release on the example script provided by @jmirabel, displaying only one mesh.

On version 1.1.0 of gepetto-viewer server, the viewer takes approximately 12% of a CPU core power when updating the display. Note that, when the python scripts end and the server stops recieving messages, the CPU loads drop to 7%, as the server is only displaying a still configuration.

The profiling gives the following results:

```python
         30388 function calls (30043 primitive calls) in 12.680 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.047    0.047   12.680   12.680 mwe.py:1(<module>)
     1000   10.126    0.010   10.126    0.010 {time.sleep}
     2007    2.401    0.001    2.401    0.001 {method 'invoke' of '_omnipy.PyObjRefObject' obj
ects}
     1000    0.015    0.000    1.975    0.002 graphical_interface_idl.py:404(applyConfiguratio
n)
     1000    0.013    0.000    0.299    0.000 graphical_interface_idl.py:410(refresh)
        1    0.000    0.000    0.115    0.115 graphical_interface_idl.py:263(createWindow)
        6    0.012    0.002    0.109    0.018 __init__.py:1(<module>)
        1    0.000    0.000    0.066    0.066 __init__.py:18(<module>)
        1    0.000    0.000    0.066    0.066 quaternion.py:18(<module>)
        1    0.001    0.001    0.066    0.066 __init__.py:106(<module>)
        1    0.000    0.000    0.056    0.056 add_newdocs.py:10(<module>)
        1    0.000    0.000    0.042    0.042 type_check.py:3(<module>)
        1    0.000    0.000    0.033    0.033 graphical_interface_idl.py:305(addMesh)
        1    0.001    0.001    0.020    0.020 _internal.py:6(<module>)
        1    0.000    0.000    0.014    0.014 __init__.py:10(<module>)
        1    0.001    0.001    0.014    0.014 py3k.py:4(<module>)
        1    0.003    0.003    0.013    0.013 pathlib.py:1(<module>)
--More--
```


The current version on the other hands takes between 18% and 20% of CPU power. However, unlike the old viewer, this CPU load does not drop when the server stops recieving messages: ```gepetto-gui``` keeps taking 20% of my CPU to display a still image.

The profiling results in the following:

```python         
30388 function calls (30043 primitive calls) in 16.724 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.053    0.053   16.725   16.725 mwe.py:1(<module>)
     1000   10.151    0.010   10.151    0.010 {time.sleep}
     2007    6.418    0.003    6.418    0.003 {method 'invoke' of '_omnipy.PyObjRefObject' obj
ects}
     1000    0.014    0.000    6.037    0.006 graphical_interface_idl.py:410(refresh)
     1000    0.015    0.000    0.333    0.000 graphical_interface_idl.py:404(applyConfiguratio
n)
        6    0.010    0.002    0.101    0.017 __init__.py:1(<module>)
        1    0.000    0.000    0.061    0.061 __init__.py:18(<module>)
        1    0.000    0.000    0.061    0.061 quaternion.py:18(<module>)
        1    0.001    0.001    0.061    0.061 __init__.py:106(<module>)
        1    0.000    0.000    0.052    0.052 add_newdocs.py:10(<module>)
        1    0.000    0.000    0.046    0.046 graphical_interface_idl.py:263(createWindow)
        1    0.000    0.000    0.038    0.038 type_check.py:3(<module>)
        1    0.000    0.000    0.027    0.027 graphical_interface_idl.py:305(addMesh)
        1    0.001    0.001    0.019    0.019 _internal.py:6(<module>)
        1    0.000    0.000    0.013    0.013 __init__.py:10(<module>)
        1    0.001    0.001    0.013    0.013 py3k.py:4(<module>)
        1    0.003    0.003    0.013    0.013 pathlib.py:1(<module>)
--More--
```

Note that there is a 4s, i.e. 30% increase in the script duration. The difference seems to come from the refresh function, that goes from 0.3s to 6s of cumulative time.

**Comment by jmirabel** [comment]
After checking the code, the default refresh rate between the two versions was changed from 20 to 30 frames per second. This may explain the increase.

If you want to dig this track further, you can try to build `gepetto-viewer-corba` from source, with a refresh rate of 20 in the current version by changing the default value of `Settings::refreshRate` in the constructor of `Settings` in `src/gui/settings.cc`.

I'll try to test it myself when I get some time.

**Comment by jmirabel** [comment]
> If you want to dig this track further, you can try to build gepetto-viewer-corba from source, with a refresh rate of 20 in the current version by changing the default value of Settings::refreshRate in the constructor of Settings in src/gui/settings.cc.

I tried and didn't see much difference...

**Comment by matthieuvigne** [comment]
As I mentionned in https://github.com/stack-of-tasks/pinocchio/issues/657 : when increasing the number of meshes to display in gepetto-gui, the execution time increases quite rapidely. For the tests I ran, I seem to have a ratio (time /  number of robots) above 2 - so when I start displaying many robots, gepetto-gui becomes very slow. Note that gepetto-gui was restarted between each test to clear the scene.
Here is an example (with URDF) if you want to try to reproduce:  [katana-gepetto.zip](https://github.com/Gepetto/gepetto-viewer-corba/files/2839827/katana-gepetto.zip)

**Comment by jmirabel** [comment]
Thanks for those files.
https://github.com/Gepetto/gepetto-viewer/pull/77 and #104 should help.

**Comment by aelkhour** [comment]
@jmirabel Could you ping us when new release is available for download through apt-get ?

**Comment by jmirabel** [comment]
I let @nim65s ping you. I don't follow binary releases myself.

**Comment by nim65s** [comment]
Will do

**Comment by jmirabel** [comment]
@nim65s mind that this has been tested by me only. I don't know who exactly is using this software from source...

**Comment by jcarpent** [comment]
@jmirabel Just to mention that with the latest release of Gepetto-gui, I also observed a serious decrease of performances. My CPU usage is always around 50% just for gepetto-gui. Leading to a very slow rendering and interaction.

**Comment by jmirabel** [comment]
Do you have an example scene ? On my computer, I do not observe the behavior you mention.

**Comment by jcarpent** [comment]
You can run the simple example from Pinocchio: https://github.com/stack-of-tasks/pinocchio/blob/devel/examples/python/gepetto-viewer.py

**Comment by jmirabel** [comment]
On my computer (laptop), it takes 8% when totally still (no event at all, like mouse movement) and ~14% when not still.
I tested this specifically with OSG 3.2.1. And I use the latest version of gepetto-gui with OSG 3.4.0.

**Comment by nim65s** [comment]
> Could you ping us when new release is available for download through apt-get ?

Hi @aelkhour 
you can now install `robotpkg-py27-qt4-gepetto-viewer-corba`, which includes those changes.

**Comment by jmirabel** [comment]
@jcarpent I encountered the case you mentioned. There was indeed a bug in my latest changes. https://github.com/Gepetto/gepetto-viewer/pull/85 solves it.

**Comment by jcarpent** [comment]
I think this issue is solved as there is no more activity on it.
