### ISSUE TITLE
Corba connection problems and segfault 

### ISSUE THREAD

**Issue by nmansard** [Gepetto/gepetto-viewer-corba#95]
I am using the latest package version of Gepetto-gui on u1604. I recently observed that the server has inconsistent behaviour depending on the network configuration.

If not network is available, the server does not want to start:
OmniORB: Warning: the local loop back interface (127.0.0.1)
is the only address available for this server.
terminate called after throwing an instance of 'CORBA::TRANSIENT'
Aborted (core dumped)

When on wireless, the server starts, but the first connection fails. After a long freeze of both server and client, the server crashes:
terminate called after throwing an instance of 'CORBA::TRANSIENT'
The client eventually manages to stay alive and finally comes back to a stable situation, of course without display capabilities.

Any clue?

**Comment by nmansard** [comment]
The bad behavior stops after rebooting, if I do not connect to the wire network.

**Comment by florent-lamiraux** [comment]
CORBA is very sensitive to network configuration variations. When I encounter this type of problem, I restart the nameserver:
`sudo service omniorb4-nameserver restart`
and usually, it solves the issue.

**Comment by jmirabel** [comment]
For the record: I think this issue could be solved by editing `/etc/omniORB.cfg`. The options _endPoint_, _endPointPublish_, _endPointNoPublish_ and _serverTransportRule_ sounds like good candidates.
