### ISSUE TITLE
STL rendering

### ISSUE THREAD

**Issue by Kevin-Giraud-Esclasse** [Gepetto/gepetto-viewer-corba#98]
Hi, 
I have a rendering problem using talos_data, it is really dark, without colors.
I am on Ubuntu 14.04
We tried this command :
```$ find /opt/openrobots/share/talos_data/meshes -iname "*.stl" -exec bash -c 'meshlabserver -i ${0} -o /tmp/foo.dae; osgconv -O daeZUpAxis /tmp/foo.dae /tmp/foo.dae.osgb; sudo mv /tmp/foo.dae.osgb ${0}.osgb' {} \;```
Colors are better but it seems orientation of each part has changed, even with  -O daeZUpAxis option
Thank you

**Comment by jmirabel** [comment]
Thanks for the report. I checked with @Kevin-Giraud-Esclasse and couldn't find a quick workaround. As this is not very important and it happens on 14.04, I will skip it.
